Repository Git-For-Geeks/Javascript-mini-projects, pull requests merged in 2022-10, with the labels that each got.

#6 Decimal To Binary Converter in js mini project
  Decimal to Binary Converter/Custom.css
  Decimal to Binary Converter/app.js
  Decimal to Binary Converter/index.html
Labels: git-for-geeks, medium, hacktoberfest-accepted

#9 simon game added
  Simon Game/game.js
  Simon Game/index.html
  Simon Game/sounds/blue.mp3
  Simon Game/sounds/green.mp3
  Simon Game/sounds/red.mp3
  Simon Game/sounds/wrong.mp3
  Simon Game/sounds/yellow.mp3
  Simon Game/styles.css
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#10 first commit
  BMI Calculator/index.html
  BMI Calculator/index.js
  BMI Calculator/style.css
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#11 Age Calculator
  Age Calculator/index.html
  Age Calculator/index1.css
  Age Calculator/index2.js
Labels: easy, git-for-geeks, hacktoberfest-accepted, hacktoberfest

#13 Sansgupta25-Currency_converter
  Currency Convertor/index.html
  Currency Convertor/script.js
  Currency Convertor/style.css
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#14 Dice Game
  Dice game/Dicee Challenge/dicee.html
  Dice game/Dicee Challenge/images/background.jpg
  Dice game/Dicee Challenge/images/dice1.png
  Dice game/Dicee Challenge/images/dice2.png
  Dice game/Dicee Challenge/images/dice3.png
  Dice game/Dicee Challenge/images/dice4.png
  Dice game/Dicee Challenge/images/dice5.png
  Dice game/Dicee Challenge/images/dice6.png
  Dice game/Dicee Challenge/images/favicon.ico
  Dice game/Dicee Challenge/index.js
  Dice game/Dicee Challenge/styles.css
  Dice game/dicee.html
  Dice game/images/background.jpg
  Dice game/images/dice1.png
  Dice game/images/dice2.png
  Dice game/images/dice3.png
  Dice game/images/dice4.png
  Dice game/images/dice5.png
  Dice game/images/dice6.png
  Dice game/images/favicon.ico
  Dice game/index.js
  Dice game/styles.css
Labels: easy, git-for-geeks, hacktoberfest-accepted, hacktoberfest

#17 Palindrome Checker
  Palindrome checker/index.html
  Palindrome checker/index.js
  Palindrome checker/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted, hacktoberfest

#18 Sansgupta25 - Tic tac toe
  Tic-tac-toe/Sample_output.png
  Tic-tac-toe/tic.css
  Tic-tac-toe/tic.html
  Tic-tac-toe/tic.js
Labels: medium, hacktoberfest-accepted, hacktoberfest

#20 GauravMKedia_Coin_Flip
  .vscode/settings.json
  Flip coin/index.html
  Flip coin/script.js
  Flip coin/style.css
Labels: git-for-geeks, hacktoberfest-accepted, hacktoberfest

#29 Sansgupta25 - Leap Year
  Leap Year/index.html
  Leap Year/script.js
  Leap Year/style.css
Labels: git-for-geeks, hacktoberfest, hard

#32 Random_Password_Generator
  Random Password Generator/Random_Password_Generator_by_Sahil/index.html
  Random Password Generator/Random_Password_Generator_by_Sahil/script.js
  Random Password Generator/Random_Password_Generator_by_Sahil/style.css
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#36 Interactive rating component
  Interactive Rating Component/images/favicon-32x32.png
  Interactive Rating Component/images/icon-star.svg
  Interactive Rating Component/images/illustration-thank-you.svg
  Interactive Rating Component/index.html
  Interactive Rating Component/index.js
  Interactive Rating Component/styles.css
Labels: easy, git-for-geeks, hacktoberfest-accepted

#39 random art
  Geometric Art Generator/index.html
  Geometric Art Generator/script.js
  Geometric Art Generator/style.css
Labels: git-for-geeks, medium

#41 Sansgupta25-Number Converter
  Number Convertor/code.js
  Number Convertor/index.html
  Number Convertor/style.css
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#43 yash14agr
  Stopwatch/index.html
  Stopwatch/style.css
  Stopwatch/style.js
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#44 Captch Generator
  Captcha Generator/index.html
  Captcha Generator/script.js
  Captcha Generator/style.css
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#49 clock
  Clock/ReadMe.md
  Clock/index.html
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#56 <Added GUI calculator>
  GUI  calculator/calculator.html
  GUI  calculator/calculator.js
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#51 Count Down Timer
  Count Down Timer/image/bg1.jpg
  Count Down Timer/index.html
Labels: medium, hacktoberfest-accepted, hacktoberfest

#62 expense tracker
  Expense Tracker/.vscode/launch.json
  Expense Tracker/expense.css
  Expense Tracker/expense.js
  Expense Tracker/index.html
Labels: git-for-geeks, medium, hacktoberfest-accepted

#64 Vertical Timeline working Properly
  Vertical Timeline/Vertical_timeline_output.png
  Vertical Timeline/index.html
  Vertical Timeline/script.js
  Vertical Timeline/style.css
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#66 Palindrome Checker
  Palindrome checker/floral.jpg
  Palindrome checker/index.html
  Palindrome checker/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted, hacktoberfest

#70 adding math game
  .vscode/settings.json
  Math Game/index.html
  Math Game/java.js
  Math Game/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted, hacktoberfest

#71 Sansgupta25-Loan Calculator
  Loan Calculator/Output_loan_calculator.png
  Loan Calculator/index.html
  Loan Calculator/script.js
  Loan Calculator/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted, hacktoberfest

#73 To do list
  simple and compund interest/simple_and_compund_intrest.js
  todo list/todo.html
  todo list/todo.js
Labels: git-for-geeks, medium, hacktoberfest-accepted, hacktoberfest

#76 Sansgupta25-Roman Number Convertor
  Roman Convertor/Output.png
  Roman Convertor/index.html
  Roman Convertor/script.js
  Roman Convertor/style.css
Labels: easy, git-for-geeks

#78 Sagar Dave- Election Map.
  Election Map/index.html
  Election Map/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted, hacktoberfest

#79 Sansgupta25-Drum set
  Drum set/images/crash.png
  Drum set/images/kick.png
  Drum set/images/snare.png
  Drum set/images/tom1.png
  Drum set/images/tom2.png
  Drum set/images/tom3.png
  Drum set/images/tom4.png
  Drum set/index.html
  Drum set/script.js
  Drum set/sounds/crash.mp3
  Drum set/sounds/kick-bass.mp3
  Drum set/sounds/snare.mp3
  Drum set/sounds/tom-1.mp3
  Drum set/sounds/tom-2.mp3
  Drum set/sounds/tom-3.mp3
  Drum set/sounds/tom-4.mp3
  Drum set/styles.css
Labels: easy, git-for-geeks, hacktoberfest-accepted

#81 Sorting Algo Visualiser
  Sorting Algo Visualiser/bubble.js
  Sorting Algo Visualiser/index.html
  Sorting Algo Visualiser/insertion.js
  Sorting Algo Visualiser/selection.js
  Sorting Algo Visualiser/sorting.js
  Sorting Algo Visualiser/style.css
Labels: easy, git-for-geeks, hacktoberfest-accepted

#80 Name Generator
  Name-Generator/app.js
  Name-Generator/index.html
  Name-Generator/style.css
Labels: hacktoberfest-accepted

#52 rgb background changer
  rgb-color-background/index.html
  rgb-color-background/myScript.js
  rgb-color-background/styles.css
Labels: hacktoberfest-accepted
